### ISSUE TITLE
Enable Markdown preview in body

### ISSUE THREAD

**Issue by phanremy** [CheatCheet/cheatcheet#27]
gem ou library JS ?

**Comment by b0rdjack** [comment]
J'aurai tendance à dire gem pour que la gestion côté Rails soit plus simple. Une libraire JS inclura forcément du travail supplémentaire pour intégrer et gérer les données côté Back-end IMHO.

**Comment by b0rdjack** [comment]
Après réflexion, pourquoi ne pas juste afficher de l'HTML, et les snippets de code sont pris en charge par [SimpleCSS](https://simplecss.org/demo#code-blocks) ?
